version: "3.9"
services:
  web:
    build: .
    image: ovo-web:dev
    command: bash -lc "flask run --host 0.0.0.0 --port 8000"
    ports: ["8000:8000"]
    environment:
      - MONGO_URI=mongodb://mongo:27017/ovo
    depends_on: [mongo]
    volumes:
      - ./:/app

  mongo:
    image: mongo:6
    ports: ["27017:27017"]
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: