name: lint-free
on: [push, pull_request]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        subdir: [web-app, machine-learning-client]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # update version(s) as needed
      - name: Install dependencies
        if: ${{ hashFiles(format('{0}/**/*.py', matrix.subdir)) != '' }}
        run: |
          cd ${{ matrix.subdir }}
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv sync --dev --python $(which python)
          pipenv shell --fancy --python $(which python)
      - name: Install tomli for pylint (runtime only)
        if: ${{ hashFiles(format('{0}/**/*.py', matrix.subdir)) != '' }}
        run: |
          cd ${{ matrix.subdir }}
          pipenv run pip install tomli typing_extensions
      - name: Lint with pylint
        if: ${{ hashFiles(format('{0}/**/*.py', matrix.subdir)) != '' }}
        run: |
          cd ${{ matrix.subdir }}
          pipenv run pylint **/*.py
      - name: Format with black
        if: ${{ hashFiles(format('{0}/**/*.py', matrix.subdir)) != '' }}
        run: |
          cd ${{ matrix.subdir }}
          pipenv run black --diff --check .

      - name: Exit pipenv shell to avoid CI hang
        if: ${{ hashFiles(format('{0}/**/*.py', matrix.subdir)) != '' }}
        run: exit 0

      - name: Re-activate pipenv environment for subsequent commands
        if: ${{ hashFiles(format('{0}/**/*.py', matrix.subdir)) != '' }}
        run: |
          cd ${{ matrix.subdir }}
          VENV_PATH=$(pipenv --venv)
          echo "$VENV_PATH/bin" >> $GITHUB_PATH


